### ISSUE TITLE
just a question 

### ISSUE THREAD

**Issue by Sorien** [Haehnchen/idea-travis-ci-test-plugin#1]
Hi, may i ask why did you stop developing this ... it would be nice to have travis CI for Php Plugins.

Sorry for bothering you.

**Comment by Haehnchen** [comment]
would be really nice, but i not got it working. only simple tests without a Project context are possible. travis enviroment dont provide the necessary stuff for "heavy tests".

here are some project example with travis:
https://github.com/pantsbuild/intellij-pants-plugin
https://github.com/KronicDeth/intellij-elixir
https://github.com/halirutan/Mathematica-IntelliJ-Plugin

**Comment by Sorien** [comment]
I think, I got it working (i can run my test suite https://github.com/Sorien/silex-idea-plugin/tree/master/tests/sk/sorien/silexplugin/tests on local linux machine openJDK1.6, ant build, idea Comunity + it need css and php plugin from Idea Ultimate) moving to travis should not be a problem couse its all based on golang plugin that is using travis CI

I'll try to setup travis in few hours and we will see...

**Comment by Sorien** [comment]
@Haehnchen it's far from perfect but working https://travis-ci.org/Sorien/silex-idea-plugin/builds/68224605
